### PR TITLE
adding async deactivate to ltelink

### PR DESCRIPTION
**Pull request by macthestack**
Added async option to blocking drop for LteLink

### CODE REVIEW

**Comment by macthestack** [comment]
Addresses issue #2

**Comment by macthestack** [comment]
updated after comment from @diondokter about deactivate subtracting active links twice. Also added an error to say if you actually deactivated lte.

In its current form you need to make sure all other links are dropped for deactivate to have an effect. This was definitely the least effort approach to the problem but maybe until something like async drop works it's also an acceptable solution since it doesn't require us to use deactivate everywhere.

**Comment by macthestack** [comment]
Open to make it less explicit if that's preferred. @diondokter ?

**Comment by diondokter** [comment]
I don't think that returning an error is a good idea because the LTE still being active is not an error condition.
So I think we should just not return anything. If you would really like this information, then it'd probably be best if a static method is added that returns the LTE status.

**Comment by macthestack** [comment]
Agree. We are only deactivating the link. Not lte necessarily.

**Comment by macthestack** [comment]
I would argue however that it's better (at least for how I would want to use it) to return an error than panicking if somethings goes wrong with the at-command.

...or is that considered so catastrophic that a reboot is always preferred? I'm pretty new to embedded programming so I'm genuinely asking.

**Comment by diondokter** [comment]
> I would argue however that it's better (at least for how I would want to use it) to return an error than panicking if somethings goes wrong with the at-command.

Yeah that's ok, that's an actual error.

> ...or is that considered so catastrophic that a reboot is always preferred? I'm pretty new to embedded programming so I'm genuinely asking.

I don't mind the unwrap in the drop function that much because I've never seen it go wrong. It's a fully internal system and the only recourse is retrying or rebooting the modem.

For retrying the user has to have the option to do that. If you only return an error in the deactivate function, then the user can't retry because the ltelink instance was thrown away.

So an error is really only useful if you can recover from it.

But still, it's better to return an error if you can (and you can't in the drop function) so that the user can decide how and when the error handling is done.
Maybe he doesn't care that the modem isn't turned off and just ignores it... Idk 🤷🏼‍♂️

**Comment by macthestack** [comment]
Makes a lot of sense.

If he (me :) ) is having a lot of state in RAM and would prefer to just restart the modem to see if that works I would definitely prefer trying to recover from it by for example restarting the modem.

**Pull request merged**
